User to moderator
AndrewCheUA/GoIT_Team_3_WEB pull request #15
Opened 2023-03-30 21:00 UTC by SSP0d

Створено в repository/ [users.py](http://users.py/) функцію update_user для зміни ролі користувача "user" на "moderator".
Додано маршрут для users в routes/ users.py.

2023-03-31 19:23 UTC, AndrewCheUA commented on app/routes/users.py
> +@router.post("/change-role", dependencies=[Depends(auth_service.get_admin_user)])
потрібно використати UserRoleFilter з utils та виконати первірку [Depends(UserRole.admin)]

2023-03-31 21:52 UTC, TT1410 requested changes

2023-03-31 21:52 UTC, TT1410 commented on app/repository/comments.py
> +    return {'message': f'Comment {comment_id} has been deleted'}
змінити

методи репо. повинні повертати або модель, або None
Вони не повинні повертати dict

2023-03-31 21:52 UTC, TT1410 commented on app/repository/comments.py
> +    return comment.scalar_one_or_none()
тут можна юзати ось так

```
comment = await scalar(
         Comment.select()
         .where(Comment.id == comment_id)
     )
return comment
     
```
результат буде такий же

2023-03-31 21:52 UTC, TT1410 commented on app/repository/users.py
> +async def update_user(user_id: int, db: AsyncSession):
Цей метод повинен називатися user_update_role, так як він оновлює лише роль юзера а не всього. І він повинен приймати любу роль аргументом, а не лише змінювати роль юзера на модератора

2023-03-31 21:52 UTC, TT1410 commented on app/routes/comments.py
> +        raise HTTPException(status_code=404, detail="Comment not found")
статус-код прописуй константою, а не цифрами

2023-04-03 20:46 UTC, AndrewCheUA commented on app/routes/users.py
> +@router.post("/change-role", dependencies=[Depends(auth_service.get_current_user), Depends(UserRole.admin)])
Нужно заменить на dependencies=[Depends(UserRoleFilter(role=UserRole.moderator))]

2023-04-03 20:48 UTC, AndrewCheUA commented on app/routes/users.py
> +from app.database.models import User, UserRole
from app.utils.filter import UserRoleFilter

2023-04-03 21:09 UTC, AndrewCheUA commented on app/database/models/image_raiting.py
> +    @role_required('admin', 'moderator')
выдает ошибку, функция role_required принимает только один аргумент, нужно или тут исправить или исправить функцию role_required

2023-04-04 21:40 UTC, closed without merging