raitings
AndrewCheUA/GoIT_Team_3_WEB pull request #37
Opened 2023-04-05 22:21 UTC by SSP0d

Реалізувати функціонал рейтингу світлин:

Користувачі можуть виставляти рейтинг світлині від 1 до 5 зірок. Рейтинг обчислюється як середнє значення оцінок всіх користувачів.
Можна тільки раз виставляти оцінку світлині для користувача.
Не можливо оцінювати свої світлини.
Модератори та адміністратори можуть переглядати та видаляти оцінки користувачів.

2023-04-07 18:21 UTC, AndrewCheUA commented on app/routes/image_ratings.py
> +@router.put("/{image_id}/{rating_id}", response_model=ImageRating)
response_model=ImageRatingCreate

2023-04-07 18:21 UTC, AndrewCheUA commented on app/routes/image_ratings.py
> +@router.post("/{image_id}", response_model=ImageRating)
response_model=ImageRatingCreate

2023-04-07 18:24 UTC, AndrewCheUA commented on app/routes/image_ratings.py
> +@router.put("/{image_id}/{rating_id}", response_model=ImageRating)
response_model=ImageRatingUpdate

2023-04-07 18:25 UTC, AndrewCheUA commented on app/routes/image_ratings.py
> +    ratings = await ImageRatingService.get_all_ratings(db_session, image_id)
db_session, image_id поменять местами

2023-04-07 18:29 UTC, AndrewCheUA reviewed
в routes/__init__.py добавить:

from . import image_ratings


router = APIRouter()

router.include_router(auth.router)
router.include_router(users.router)
router.include_router(images.router)
router.include_router(image_formats.router)
router.include_router(image_comments.router)
router.include_router(image_ratings.router)


__all__ = (
    'router',
)

2023-04-07 18:39 UTC, AndrewCheUA commented on app/database/models/images.py
> +    async def get_image_by_id(db_session: Session, image_id: int) -> Optional["Image"]:
вместо Session нужна AsyncSession

2023-04-07 18:39 UTC, AndrewCheUA commented on app/database/models/image_raiting.py
> +
доюавить импорт from sqlalchemy.ext.asyncio import AsyncSession

2023-04-07 18:40 UTC, AndrewCheUA commented on app/database/models/images.py
добавить импорт from sqlalchemy.ext.asyncio import AsyncSession

2023-04-07 18:41 UTC, AndrewCheUA commented on app/database/models/images.py
> +        return await db_session.query(Image).filter(Image.id == image_id).first()
db_session.scalar(select(Image).filter(Image.id == image_id))

2023-04-07 19:28 UTC, AndrewCheUA commented on app/services/image_ratings.py
> +        await db.commit()
добавить await db.refresh(rating)

2023-04-07 19:54 UTC, AndrewCheUA commented on app/schemas/image_raitings.py
> +        orm_mode = True
Для вывода нужено добавить отдельный класс

class ImageRatingResponse(DateTimeModelMixin, ImageRatingCreate, IDModelMixin):

    class Config:
        orm_mode = True

2023-04-07 19:55 UTC, AndrewCheUA commented on app/schemas/image_raitings.py
> +    user_id: int
user_id: int нужно удалить, функция должна забирать его из current user

2023-04-07 19:58 UTC, AndrewCheUA commented on app/routes/image_ratings.py
> +    rating = await ImageRatingService.create(db_session, **rating_data.dict(), image_id=image_id, user_id=current_user.id)
Заменить на: rating = await ImageRatingService.create(rating_data.rating, rating_data.image_id, current_user.id, db_session)

В текущей версии два раза image_id залетает в ImageRatingService.create()

2023-04-07 20:03 UTC, AndrewCheUA commented on app/services/image_ratings.py
> +        rating = await db.query(ImageRating).filter(ImageRating.id == rating_id).first()
db_session.scalar(select(Image).filter(ImageRating.id == rating_id))

db.query выдает ошибку AttributeError: 'AsyncSession' object has no attribute 'query'

2023-04-07 20:26 UTC, AndrewCheUA commented on app/routes/image_ratings.py
> +    rating = await rating.update(db_session, **rating_data.dict())
AttributeError: 'ImageRating' object has no attribute 'update'

(db_session, **rating_data.dict()) не работает, так как rating.update принимает асинхронные коннект к базе

2023-04-07 20:56 UTC, SSP0d commented on app/database/models/images.py
done

2023-04-07 20:56 UTC, SSP0d commented on app/database/models/images.py
> +    async def get_image_by_id(db_session: Session, image_id: int) -> Optional["Image"]:
done

2023-04-07 20:56 UTC, SSP0d commented on app/routes/image_ratings.py
> +    ratings = await ImageRatingService.get_all_ratings(db_session, image_id)
done

2023-04-07 20:56 UTC, SSP0d commented on app/routes/image_ratings.py
> +@router.get("/{image_id}/ratings", response_model=List[ImageRating])
done

2023-04-07 20:56 UTC, SSP0d commented on app/routes/image_ratings.py
> +@router.put("/{image_id}/{rating_id}", response_model=ImageRating)
done

2023-04-07 20:56 UTC, SSP0d commented on app/routes/image_ratings.py
> +@router.post("/{image_id}", response_model=ImageRating)
done

2023-04-07 20:58 UTC, SSP0d commented on app/database/models/images.py
> +        return await db_session.query(Image).filter(Image.id == image_id).first()
done

2023-04-07 20:59 UTC, SSP0d commented on app/services/image_ratings.py
> +        await db.commit()
done

2023-04-07 21:01 UTC, SSP0d commented on app/schemas/image_raitings.py
> +        orm_mode = True
done

2023-04-07 21:02 UTC, SSP0d commented on app/schemas/image_raitings.py
> +    user_id: int
done

2023-04-07 21:05 UTC, SSP0d commented on app/routes/image_ratings.py
> +    rating = await ImageRatingService.create(db_session, **rating_data.dict(), image_id=image_id, user_id=current_user.id)
done

2023-04-07 21:06 UTC, SSP0d commented on app/services/image_ratings.py
> +        rating = await db.query(ImageRating).filter(ImageRating.id == rating_id).first()
done

2023-04-07 21:15 UTC, SSP0d commented on app/routes/image_ratings.py
> +    rating = await rating.update(db_session, **rating_data.dict())
done

2023-04-07 21:32 UTC, AndrewCheUA commented on app/services/image_ratings.py
> +        return ratings.fetchall()
ValueError: [TypeError('cannot convert dictionary update sequence element #0 to a sequence'), TypeError('vars() argument must have __dict__ attribute')]

Лучше заменить на запрос:
ratings = await db.scalars(select(ImageRating).filter(ImageRating.image_id == image_id))

        return ratings.all()  # noqa

2023-04-07 21:33 UTC, AndrewCheUA commented on app/routes/image_ratings.py
> +        db_session=Depends(get_db)
db_session: AsyncSession = Depends(get_db)

2023-04-07 21:33 UTC, AndrewCheUA commented on app/routes/image_ratings.py
> +async def get_all_image_ratings(image_id: int, db=Depends(get_db)):
db_session: AsyncSession = Depends(get_db)

2023-04-08 08:31 UTC, AndrewCheUA requested changes
Методы из images и users в databes нужно перенести в repository.
Вся работа с базой данных из services тоже должна быть реализована в repository

2023-04-08 19:45 UTC, AndrewCheUA approved these changes

2023-04-08 19:45 UTC, merged